In [63]:
import pandas as pd
import numpy as np


In [5]:
df=pd.read_csv('DS1_C9_S7_Project_AbsenteeismAtWork_Data.csv',sep=';')
df

ID  Reason for absence  Month of absence  Day of the week  Seasons  \
0    11                  26                 7                3        1   
1    36                   0                 7                3        1   
2     3                  23                 7                4        1   
3     7                   7                 7                5        1   
4    11                  23                 7                5        1   
..   ..                 ...               ...              ...      ...   
735  11                  14                 7                3        1   
736   1                  11                 7                3        1   
737   4                   0                 0                3        1   
738   8                   0                 0                4        2   
739  35                   0                 0                6        3   

     Transportation expense  Distance from Residence to Work  Service time  \
0                       289                               36            13   
1                       118                               13            18   
2                       179                               51            18   
3                       279                                5            14   
4                       289                               36            13   
..                      ...                              ...           ...   
735                     289                               36            13   
736                     235                               11            14   
737                     118                               14            13   
738                     231                               35            14   
739                     179                               45            14   

     Age  Work load Average/day   ...  Disciplinary failure  Education  Son  \
0     33                 239.554  ...                     0          1    2   
1     50                 239.554  ...                     1          1    1   
2     38                 239.554  ...                     0          1    0   
3     39                 239.554  ...                     0          1    2   
4     33                 239.554  ...                     0          1    2   
..   ...                     ...  ...                   ...        ...  ...   
735   33                 264.604  ...                     0          1    2   
736   37                 264.604  ...                     0          3    1   
737   40                 271.219  ...                     0          1    1   
738   39                 271.219  ...                     0          1    2   
739   53                 271.219  ...                     0          1    1   

     Social drinker  Social smoker  Pet  Weight  Height  Body mass index  \
0                 1              0    1      90     172               30   
1                 1              0    0      98     178               31   
2                 1              0    0      89     170               31   
3                 1              1    0      68     168               24   
4                 1              0    1      90     172               30   
..              ...            ...  ...     ...     ...              ...   
735               1              0    1      90     172               30   
736               0              0    1      88     172               29   
737               1              0    8      98     170               34   
738               1              0    2     100     170               35   
739               0              0    1      77     175               25   

     Absenteeism time in hours  
0                            4  
1                            0  
2                            2  
3                            4  
4                            2  
..                         ...  
735                          8  
736                          4  
737     

In [7]:
df.to_csv('project-ml.csv')


In [11]:
df.columns=df.columns.str.replace(' ','_')
df.columns

Index(['ID', 'Reason_for_absence', 'Month_of_absence', 'Day_of_the_week',
       'Seasons', 'Transportation_expense', 'Distance_from_Residence_to_Work',
       'Service_time', 'Age', 'Work_load_Average/day_', 'Hit_target',
       'Disciplinary_failure', 'Education', 'Son', 'Social_drinker',
       'Social_smoker', 'Pet', 'Weight', 'Height', 'Body_mass_index',
       'Absenteeism_time_in_hours'],
      dtype='object')

In [13]:
df.head()

ID  Reason_for_absence  Month_of_absence  Day_of_the_week  Seasons  \
0  11                  26                 7                3        1   
1  36                   0                 7                3        1   
2   3                  23                 7                4        1   
3   7                   7                 7                5        1   
4  11                  23                 7                5        1   

   Transportation_expense  Distance_from_Residence_to_Work  Service_time  Age  \
0                     289                               36            13   33   
1                     118                               13            18   50   
2                     179                               51            18   38   
3                     279                                5            14   39   
4                     289                               36            13   33   

   Work_load_Average/day_  ...  Disciplinary_failure  Education  Son  \
0                 239.554  ...                     0          1    2   
1                 239.554  ...                     1          1    1   
2                 239.554  ...                     0          1    0   
3                 239.554  ...                     0          1    2   
4                 239.554  ...                     0          1    2   

   Social_drinker  Social_smoker  Pet  Weight  Height  Body_mass_index  \
0               1              0    1      90     172               30   
1               1              0    0      98     178               31   
2               1              0    0      89     170               31   
3               1              1    0      68     168               24   
4               1              0    1      90     172               30   

   Absenteeism_time_in_hours  
0                          4  
1                          0  
2                          2  
3                          4  
4                          2  

[5 rows x 21 columns]

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 740 entries, 0 to 739
Data columns (total 21 columns):
 #   Column                           Non-Null Count  Dtype  
---  ------                           --------------  -----  
 0   ID                               740 non-null    int64  
 1   Reason_for_absence               740 non-null    int64  
 2   Month_of_absence                 740 non-null    int64  
 3   Day_of_the_week                  740 non-null    int64  
 4   Seasons                          740 non-null    int64  
 5   Transportation_expense           740 non-null    int64  
 6   Distance_from_Residence_to_Work  740 non-null    int64  
 7   Service_time                     740 non-null    int64  
 8   Age                              740 non-null    int64  
 9   Work_load_Average/day_           740 non-null    float64
 10  Hit_target                       740 non-null    int64  
 11  Disciplinary_failure             740 non-null    int64  
 12  Education             

In [17]:
df.isnull().sum()

ID                                 0
Reason_for_absence                 0
Month_of_absence                   0
Day_of_the_week                    0
Seasons                            0
Transportation_expense             0
Distance_from_Residence_to_Work    0
Service_time                       0
Age                                0
Work_load_Average/day_             0
Hit_target                         0
Disciplinary_failure               0
Education                          0
Son                                0
Social_drinker                     0
Social_smoker                      0
Pet                                0
Weight                             0
Height                             0
Body_mass_index                    0
Absenteeism_time_in_hours          0
dtype: int64

In [19]:
df['Seasons'].unique()

array([1, 4, 2, 3], dtype=int64)

In [ ]:
# 1-summer
# 2-autom
# 3-winter
# 4-spring
# pd.cut sesaon_c

In [21]:
df['Day_of_the_week'].unique()

array([3, 4, 5, 6, 2], dtype=int64)

In [25]:
bins=[0,1,2,3,4,5,6,7]
labels=['sun','mon','tue','wed','thurs','fri','sat']
df['Day_of_the_week_c']=pd.cut(df['Day_of_the_week'],bins=bins,labels=labels)

In [27]:
df

ID  Reason_for_absence  Month_of_absence  Day_of_the_week  Seasons  \
0    11                  26                 7                3        1   
1    36                   0                 7                3        1   
2     3                  23                 7                4        1   
3     7                   7                 7                5        1   
4    11                  23                 7                5        1   
..   ..                 ...               ...              ...      ...   
735  11                  14                 7                3        1   
736   1                  11                 7                3        1   
737   4                   0                 0                3        1   
738   8                   0                 0                4        2   
739  35                   0                 0                6        3   

     Transportation_expense  Distance_from_Residence_to_Work  Service_time  \
0                       289                               36            13   
1                       118                               13            18   
2                       179                               51            18   
3                       279                                5            14   
4                       289                               36            13   
..                      ...                              ...           ...   
735                     289                               36            13   
736                     235                               11            14   
737                     118                               14            13   
738                     231                               35            14   
739                     179                               45            14   

     Age  Work_load_Average/day_  ...  Education  Son  Social_drinker  \
0     33                 239.554  ...          1    2               1   
1     50                 239.554  ...          1    1               1   
2     38                 239.554  ...          1    0               1   
3     39                 239.554  ...          1    2               1   
4     33                 239.554  ...          1    2               1   
..   ...                     ...  ...        ...  ...             ...   
735   33                 264.604  ...          1    2               1   
736   37                 264.604  ...          3    1               0   
737   40                 271.219  ...          1    1               1   
738   39                 271.219  ...          1    2               1   
739   53                 271.219  ...          1    1               0   

     Social_smoker  Pet  Weight  Height  Body_mass_index  \
0                0    1      90     172               30   
1                0    0      98     178               31   
2                0    0      89     170               31   
3                1    0      68     168               24   
4                0    1      90     172               30   
..             ...  ...     ...     ...              ...   
735              0    1      90     172               30   
736              0    1      88     172               29   
737              0    8      98     170               34   
738              0    2     100     170               35   
739              0    1      77     175               25   

     Absenteeism_time_in_hours  Day_of_the_week_c  
0                            4                tue  
1                            0                tue  
2                            2                wed  
3                            4              thurs  
4                            2              thurs  
..                         ...                ...  
735                          8                tue  
736                          4                tue  
737                          0                tue  
738                          0                wed

In [31]:
df['Education'].unique()

array([1, 3, 2, 4], dtype=int64)

In [33]:
# high-school
# ug
# pg
# masters
df['Disciplinary_failure'].unique()
Social_drinker
Social_smoker

array([0, 1], dtype=int64)

In [35]:
df['Reason_for_absence'].unique()

array([26,  0, 23,  7, 22, 19,  1, 11, 14, 21, 10, 13, 28, 18, 25, 24,  6,
       27, 17,  8, 12,  5,  9, 15,  4,  3,  2, 16], dtype=int64)

In [51]:
threshold=[14,17,21]
labels=['group1','group2','group3','group4']
# functions to assign labels based on conditions
def assign_label(values):
    if values<=threshold[0]:
        return labels[0]
    elif values<=threshold[1]:
         return labels[1]
    elif values<=threshold[2]:
         return labels[2]
    else:
        return labels[3]
# apply the function to the columns and create a new columns to create a variable



In [53]:
df['Reason_for_absence_c']=df['Reason_for_absence'].apply(assign_label)


In [55]:
df['Reason_for_absence_c'].unique()

array(['group4', 'group1', 'group3', 'group2'], dtype=object)

In [57]:
df['Absenteeism_time_in_hours'].unique()

array([  4,   0,   2,   8,  40,   1,   7,   3,  32,   5,  16,  24,  64,
        56,  80, 120, 112, 104,  48], dtype=int64)

In [59]:
df['Absenteeism_time_in_hours'].mean()

6.924324324324324

In [65]:
df['Absenteeism_time_in_hours_c']=np.where(df['Absenteeism_time_in_hours']>df['Absenteeism_time_in_hours'].mean(),'high_absent','low_absent')

In [67]:
df['Absenteeism_time_in_hours_c'].unique()

array(['low_absent', 'high_absent'], dtype=object)

In [69]:
df['Hit_target'].unique()

array([ 97,  92,  93,  95,  99,  96,  94,  98,  81,  88, 100,  87,  91],
      dtype=int64)

In [71]:
df['Hit_target'].median()

95.0

In [75]:
df['Hit_target_c']=np.where(df['Hit_target']>df['Hit_target'].mean(),'acheived','not_acheived')

In [77]:
df['Hit_target_c'].unique()

array(['acheived', 'not_acheived'], dtype=object)

In [81]:
df['Age'].unique()

array([33, 50, 38, 39, 28, 36, 34, 37, 41, 47, 29, 48, 32, 27, 43, 40, 31,
       30, 49, 58, 46, 53], dtype=int64)

In [83]:
threshold=[30,35,40,45,50,55]
labels=['25 to 30','30 to 35','35 to 40','40 to 45','45 to 50','50 to 55','55 to 60']
def label_assign(values):
    if values<=threshold[0]:
        return labels[0]
    elif values<=threshold[1]:
        return labels[1]
    elif values<=threshold[2]:
        return labels[2]
    elif values<=threshold[3]:
        return labels[3]
    elif values<=threshold[4]:
        return labels[4]
    elif values<=threshold[5]:
        return labels[5]
    else:
        return labels[6]

In [85]:
df['Age_c']=df['Age'].apply(label_assign)

In [87]:
df['Age_c'].unique()

array(['30 to 35', '45 to 50', '35 to 40', '25 to 30', '40 to 45',
       '55 to 60', '50 to 55'], dtype=object)